### PR TITLE
JVM-1686: materialized AllocateNodes copy BCI from original node

### PR DESCRIPTION
**Pull request by caojoshua**
Materialized AllocateNode's JVMState currently copied the BCI from GraphKit. The BCI should instead be the BCI from the original AllocateNode.

### CODE REVIEW

**Comment by navyxliu** [comment]
here is ctxt Parsing method virtual jobject Str.strBuilderRepro()
```
Parsing block #0 at bci [0,13), successors: 
 @ bci:0 new
 @ bci:3 dup
 @ bci:4 bipush
 @ bci:6 invokespecial
PEA materializes a virtual object: 26
ciInstanceKlass: java/lang/StringBuilder
flt# 0 = 0 // count
flt# 1 = 0 // coder
flt# 2 = 0 // maybeLatin1
flt# 3 = 0 // value
new object:  65  CheckCastPP  === 62 60  [[ ]]   Oop:java/lang/StringBuilder (java/io/Serializable,java/lang/Comparable,java/lang/CharSequence,java/lang/Appendable):NotNull:exact * !jvms: Str::strBuilderRepro @ bci:6 (line 3)
 @ bci:9 invokevirtual
 @ bci:12 areturn
}
```

In PhaseStringOpts::replace_string_concat, sc->begin() is the AllocateNode of StringBuilder. 
With PEA, it points to the cloned StringBuilder with bci=6.  This patch correct bci with the original JVMState's bci, or 0.

The inputs of `bytecode new` is 0. If we reset bci() to bytecode `new`, sp() >= 0 always true. therefore, we don't need to worry about sp() of JVMState.

**Comment by caojoshua** [comment]
Agree we don't need to worry about SP here. SP inherited from GraphKit's JVM state should be correct. I think that PEAState in JVM State needs to be updated.

**Review by navyxliu — APPROVED** [review]
LGTM. 

when we generate uncommon_trap for StringBuilder.toString(), we encounter inconsistency between sp and bci(). if we adjust bci to the original `AllocateNode', it means that bci() points to bytecode `new`. its inputs is 0.  sp() >= 0 is always true.

**Comment by navyxliu** [comment]
I do update the PEAState of GraphKit's jvmstate in PEAState::materialize(). 
so far, i think it's fine.

**Pull request merged**
